[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
covantic = "52KrSMg3rsbtRw3FchxJ9jRwRzQmWcDzg1AiiHHHXz1D"

[programs.localnet]
covantic = "52KrSMg3rsbtRw3FchxJ9jRwRzQmWcDzg1AiiHHHXz1D"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec vitest run"

[test]
startup_wait = 5000
