[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
covantic = "HrLqdNdxUJq4pgsL4NsUqzfYrGxR7Hy9PHGEeHnj3skL"

[programs.localnet]
covantic = "HrLqdNdxUJq4pgsL4NsUqzfYrGxR7Hy9PHGEeHnj3skL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec vitest run"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
